/**
 * Datos de eventos EPIS-UPT
 *
 * Campos disponibles por evento:
 *   id                  – Identificador único (string)
 *   nombre              – Nombre del evento
 *   categoria           – Hackathon | Congreso | Feria | Foro | Seminario | Exposición | Webinar
 *   institucion         – Institución organizadora
 *   lugar               – Lugar / sede del evento
 *   fechaEvento         – Fecha del evento (YYYY-MM-DD)
 *   duracion            – Duración (ej. "1 día", "3 días", "2 horas")
 *   cierreInscripcion   – Fecha límite de inscripción (YYYY-MM-DD, puede estar vacío)
 *   modalidad           – Presencial | Virtual | Híbrido
 *   estado              – Confirmado | Próximo | Pendiente | Realizado | Finalizado
 *   link                – URL del evento (puede estar vacío)
 *   responsable         – Persona responsable (puede estar vacío)
 *   repetirProximoAnio  – true | false
 *   repetible           – "Sí" | "" 
 *   notas               – Observaciones adicionales (puede estar vacío)
 *   imagen              – (OPCIONAL) Ruta a una imagen personalizada del evento.
 *                         Ejemplos: 'img/mi-afiche.jpg'  /  'img/evento-015.png'
 *                         Si se omite o queda vacío (""), se mostrará automáticamente
 *                         la imagen predeterminada según la categoría del evento.
 */
const eventosData = [
    {
        id: "001",
        nombre: "Peru HUB Digital",
        categoria: "Exposición",
        institucion: "Escuela Naval",
        lugar: "Lima",
        fechaEvento: "2024-11-14",
        duracion: "1 día",      
        cierreInscripcion: "2024-11-05",
        modalidad: "Presencial",
        estado: "Pendiente",
        link: "http://peruhubdigital-universitario.unity.pe/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Evento anual de tecnología",
        imagen: ""
    },
    {
        id: "002",
        nombre: "Concytec – Feria",
        categoria: "Foro",
        institucion: "PCM",
        lugar: "Lima",
        fechaEvento: "2024-12-05",
        duracion: "1 día",      
        cierreInscripcion: "2024-11-25",
        modalidad: "Híbrido",
        estado: "Confirmado",
        link: "https://eureka-etapafinal.concytec.gob.pe/eureka/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "",
        imagen: ""
    },
    {
        id: "003",
        nombre: "Concurso de Programación UNJBG - XXVI CIIS",
        categoria: "Hackathon",
        institucion: "UNJBG",
        lugar: "Tacna / Laboratorio A (3er piso, ESIS - UNJBG)",
        fechaEvento: "2025-01-20",
        duracion: "1 día",      
        cierreInscripcion: "2025-01-10",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://ciistacna.com/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Participación universitaria",
        imagen: ""
    },
    {
        id: "004",
        nombre: "Concurso de programado UPT V Programming Contest",
        categoria: "Hackathon",
        institucion: "UPT",
        lugar: "Tacna / Campus Capanique UPT",
        fechaEvento: "2026-11-13",
        duracion: "1 día",      
        cierreInscripcion: "2026-11-13",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://www.facebook.com/catec.pe/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Participación universitaria",
        imagen: ""
    },
    {
        id: "005",
        nombre: "La Hackathon Innova Sur 2025 - tercera edición",
        categoria: "Hackathon",
        institucion: "Universidad Católica San Pablo",
        lugar: "Tacna / Edificio Bustamante 301-302. UCSP",
        fechaEvento: "2025-10-10",
        duracion: "1 día",      
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://ucsp.edu.pe/agenda/iii-hackathon-innovasur/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Edición anterior exitosa",
        imagen: ""
    },
    {
        id: "006",
        nombre: "Training Camp UCSP",
        categoria: "Hackathon",
        institucion: "Universidad Católica San Pablo",
        lugar: "Tacna / Edificio Bustamante 301-302. UCSP",
        fechaEvento: "2025-11-04",
        duracion: "1 día",      
        cierreInscripcion: "2025-11-09",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://dc.ucsp.edu.pe/cursos/training-camp/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Campamento de Programación Competitiva",
        imagen: ""
    },
    {
        id: "007",
        nombre: "XVI Conferencia INFONOR-CHILE 2025",
        categoria: "Congreso",
        institucion: "Universidad de Tarapacá",
        lugar: "Chile",
        fechaEvento: "2025-09-03",
        duracion: "1 día",      
        cierreInscripcion: "2025-09-05",
        modalidad: "Presencial",
        estado: "Realizado",
        link: "https://infonor2025.uta.cl/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Muy buena convocatoria",
        imagen: ""
    },
    {
        id: "008",
        nombre: "I FERIA DE INVESTIGACIÓN CIENTÍFICA",
        categoria: "Feria",
        institucion: "Campus Capanique UPT",
        lugar: "Tacna",
        fechaEvento: "2025-11-13",
        duracion: "1 día",
        cierreInscripcion: "2025-11-14",
        modalidad: "Presencial",
        estado: "Realizado",
        link: "https://www.upt.edu.pe/upt/web/home/not_detalle/100000000/54423217",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "",
        imagen: ""
    },
    {
        id: "009",
        nombre: "Huawei ICT Competition",
        categoria: "Hackathon",
        institucion: "Huawei",
        lugar: "China",
        fechaEvento: "2025-01-01",
        duracion: "1 día",      
        cierreInscripcion: "2025-02-28",
        modalidad: "Virtual",
        estado: "Próximo",
        link: "https://www.huawei.com/minisite/ict-competition-2024-2025-global/en/index.html",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "",
        imagen: ""
    },
    {
        id: "010",
        nombre: "XXVII CONCURSO DE PROYECTOS",
        categoria: "Seminario",
        institucion: "Campus Capanique UPT",
        lugar: "Tacna",
        fechaEvento: "2025-12-01",
        duracion: "1 día",      
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://www.facebook.com/uptsistemas/posts/resultados-del-xxvii-concurso-de-proyectos-epis-2025-ii/1448267327305967/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Rotativo por regiones",
        imagen: ""
    },
    {
        id: "011",
        nombre: "Hackaton Challenge 2026 – Paqarina Wasi",
        categoria: "Hackathon",
        institucion: "UNSAAC",
        lugar: "Cuzco",
        fechaEvento: "2026-02-23",
        duracion: "1 día",      
        cierreInscripcion: "2026-02-27",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://www.facebook.com/paqarinawasicusco/posts/-hackaton-challenge-2026-paqarina-wasitu-idea-puede-convertirse-en-un-prototipo-/122212460906359675/",
        responsable: "",
        repetible: "",
        notas: "",
        imagen: ""
    },
    {
        id: "012",
        nombre: "Dev-Fest Tacna",
        categoria: "Seminario",
        institucion: "Google",
        lugar: "Tacna",
        fechaEvento: "2025-11-22",
        duracion: "1 día",      
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://devfest.gdgtacna.com/",
        responsable: "",
        repetible: "",
        notas: "",
        imagen: ""
    },
    {
        id: "013",
        nombre: "1er Congreso Internacional de IA y Transformación Digital",
        categoria: "Seminario",
        institucion: "",
        lugar: "Tacna",
        fechaEvento: "2025-09-19",
        duracion: "1 día",      
        cierreInscripcion: "2025-09-20",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://www.sistemasdelsur.edu.pe/congreso/",
        responsable: "",
        repetible: "",
        notas: "",
        imagen: ""
    },
    {
        id: "014",
        nombre: "HACKATON PLATEADA +50",
        categoria: "Hackathon",
        institucion: "UP - Hackaton Plateada +50",
        lugar: "Tacna",
        fechaEvento: "2025-09-19",
        duracion: "1 día",      
        cierreInscripcion: "2025-09-20",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://ecosistemaplateado.pe/evento/hackaton-plateada/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "",
        imagen: ""
    },
    {
        id: "015",
        nombre: "Road to Build with AI",
        categoria: "Hackathon",
        institucion: "Google For Developers / GDG Tacna",
        lugar: "Tacna",
        fechaEvento: "2026-04-11",
        duracion: "1 día",
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://gdg.community.dev/events/details/google-gdg-tacna-presents-road-to-build-with-ai-tacna-2026/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "",
        imagen: ""
    },
    {
        id: "016",
        nombre: "Build with AI Tacna 2026",
        categoria: "Exposición",
        institucion: "Google For Developers / GDG Tacna",
        lugar: "Tacna",
        fechaEvento: "2026-03-28",
        duracion: "1 día",
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://gdg.community.dev/events/details/google-gdg-tacna-presents-build-with-ai-tacna-2026/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "",
        imagen: "img/16.webp"
    },
    {
        id: "017",
        nombre: "Programa de Extensión Universitaria Ciencia del Dato PEU CD",
        categoria: "Webinar",
        institucion: "INEI",
        lugar: "Tacna",
        fechaEvento: "2026-04-07",
        duracion: "1 día",
        cierreInscripcion: "",
        modalidad: "Virtual",
        estado: "Confirmado",
        link: "https://site2.q10.com/Clase/90d76704-1c02-47ba-b14c-5a5777138e21/Enlace?aplentId=aeba24e5-3082-4309-849a-342e7782f27e",
        responsable: "Dr. Gaspar Morán Flores",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "16:00 pm a 17:00 pm",
        imagen: ""
    }
];
