const eventosData = [
    {
        id: "001",
        nombre: "Peru HUB Digital",
        categoria: "Exposición",
        institucion: "Escuela Naval",
        lugar: "Lima",
        fechaEvento: "2024-11-14",
        duracion: "1 día",      
        cierreInscripcion: "2024-11-05",
        modalidad: "Presencial",
        estado: "Pendiente",
        link: "http://peruhubdigital-universitario.unity.pe/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Evento anual de tecnología"
    },
    {
        id: "002",
        nombre: "Concytec – Feria",
        categoria: "Foro",
        institucion: "PCM",
        lugar: "Lima",
        fechaEvento: "2024-12-05",
        duracion: "1 día",      
        cierreInscripcion: "2024-11-25",
        modalidad: "Híbrido",
        estado: "Confirmado",
        link: "https://eureka-etapafinal.concytec.gob.pe/eureka/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: ""
    },
    {
        id: "003",
        nombre: "Concurso de Programación UNJBG - XXVI CIIS",
        categoria: "Hackathon",
        institucion: "UNJBG",
        lugar: "Tacna / Laboratorio A (3er piso, ESIS - UNJBG)",
        fechaEvento: "2025-01-20",
        duracion: "1 día",      
        cierreInscripcion: "2025-01-10",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://ciistacna.com/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Participación universitaria"
    },
    {
        id: "004",
        nombre: "Concurso de programado UPT V Programming Contest",
        categoria: "Hackathon",
        institucion: "UPT",
        lugar: "Tacna / Campus Capanique UPT",
        fechaEvento: "2026-11-13",
        duracion: "1 día",      
        cierreInscripcion: "2026-11-13",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://www.facebook.com/catec.pe/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Participación universitaria"
    },
    {
        id: "005",
        nombre: "La Hackathon Innova Sur 2025 - tercera edición",
        categoria: "Hackathon",
        institucion: "Universidad Católica San Pablo",
        lugar: "Tacna / Edificio Bustamante 301-302. UCSP",
        fechaEvento: "2025-10-10",
        duracion: "1 día",      
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://ucsp.edu.pe/agenda/iii-hackathon-innovasur/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Edición anterior exitosa"
    },
    {
        id: "006",
        nombre: "Training Camp UCSP",
        categoria: "Hackathon",
        institucion: "Universidad Católica San Pablo",
        lugar: "Tacna / Edificio Bustamante 301-302. UCSP",
        fechaEvento: "2025-11-04",
        duracion: "1 día",      
        cierreInscripcion: "2025-11-09",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://dc.ucsp.edu.pe/cursos/training-camp/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Campamento de Programación Competitiva"
    },
    {
        id: "007",
        nombre: "XVI Conferencia INFONOR-CHILE 2025",
        categoria: "Congreso",
        institucion: "Universidad de Tarapacá",
        lugar: "Chile",
        fechaEvento: "2025-09-03",
        duracion: "1 día",      
        cierreInscripcion: "2025-09-05",
        modalidad: "Presencial",
        estado: "Realizado",
        link: "https://infonor2025.uta.cl/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Muy buena convocatoria"
    },
    {
        id: "008",
        nombre: "I FERIA DE INVESTIGACIÓN CIENTÍFICA",
        categoria: "Feria",
        institucion: "Campus Capanique UPT",
        lugar: "Tacna",
        fechaEvento: "2025-11-13",
        duracion: "1 día",
        cierreInscripcion: "2025-11-14",
        modalidad: "Presencial",
        estado: "Realizado",
        link: "https://www.upt.edu.pe/upt/web/home/not_detalle/100000000/54423217",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: ""
    },
    {
        id: "009",
        nombre: "Huawei ICT Competition",
        categoria: "Hackathon",
        institucion: "Huawei",
        lugar: "China",
        fechaEvento: "2025-01-01",
        duracion: "1 día",      
        cierreInscripcion: "2025-02-28",
        modalidad: "Virtual",
        estado: "Próximo",
        link: "https://www.huawei.com/minisite/ict-competition-2024-2025-global/en/index.html",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: ""
    },
    {
        id: "010",
        nombre: "XXVII CONCURSO DE PROYECTOS",
        categoria: "Seminario",
        institucion: "Campus Capanique UPT",
        lugar: "Tacna",
        fechaEvento: "2025-12-01",
        duracion: "1 día",      
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://www.facebook.com/uptsistemas/posts/resultados-del-xxvii-concurso-de-proyectos-epis-2025-ii/1448267327305967/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: "Rotativo por regiones"
    },
    {
        id: "011",
        nombre: "Hackaton Challenge 2026 – Paqarina Wasi",
        categoria: "Hackathon",
        institucion: "UNSAAC",
        lugar: "Cuzco",
        fechaEvento: "2026-02-23",
        duracion: "1 día",      
        cierreInscripcion: "2026-02-27",
        modalidad: "Presencial",
        estado: "Próximo",
        link: "https://www.facebook.com/paqarinawasicusco/posts/-hackaton-challenge-2026-paqarina-wasitu-idea-puede-convertirse-en-un-prototipo-/122212460906359675/",
        responsable: "",
        repetible: "",
        notas: ""
    },
    {
        id: "012",
        nombre: "Dev-Fest Tacna",
        categoria: "Seminario",
        institucion: "Google",
        lugar: "Tacna",
        fechaEvento: "2025-11-22",
        duracion: "1 día",      
        cierreInscripcion: "",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://devfest.gdgtacna.com/",
        responsable: "",
        repetible: "",
        notas: ""
    },
    {
        id: "013",
        nombre: "1er Congreso Internacional de IA y Transformación Digital",
        categoria: "Seminario",
        institucion: "",
        lugar: "Tacna",
        fechaEvento: "2025-09-19",
        duracion: "1 día",      
        cierreInscripcion: "2025-09-20",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://www.sistemasdelsur.edu.pe/congreso/",
        responsable: "",
        repetible: "",
        notas: ""
    },
    {
        id: "014",
        nombre: "HACKATON PLATEADA +50",
        categoria: "Hackathon",
        institucion: "UP - Hackaton Plateada +50",
        lugar: "Tacna",
        fechaEvento: "2025-09-19",
        duracion: "1 día",      
        cierreInscripcion: "2025-09-20",
        modalidad: "Presencial",
        estado: "Confirmado",
        link: "https://ecosistemaplateado.pe/evento/hackaton-plateada/",
        responsable: "",
        repetirProximoAnio: true,
        repetible: "Sí",
        notas: ""
    }
];